# Bật chuột: Cho phép cuộn xem log, click chọn pane, kéo resize viền pane
set -g mouse on

# Tăng buffer cuộn lịch sử lên 50,000 dòng
set -g history-limit 50000

# Giữ màu sắc chuẩn 256color cho terminal
set -g default-terminal "screen-256color"
